### ISSUE TITLE
chore: deal with CSS animation code

### ISSUE THREAD

**Issue by webcrawls** [Nowheres2go/erinoisidori.online-redux#11]
this snippet was taken from the `fix/marquee` branch during some CSS styling cleanups. i wanted to get it out of the way for simplicity but not to delete it entirely, so for posterity:

```css
/*main {*/
/*    background: linear-gradient(0deg, #a8a8a8, #bbbbbb, #d9d9d9, #e8e8e8, #fde5a2);*/
/*    background-size: 1200% 1200%;*/

/*    -webkit-animation: AnimationName 20s ease infinite;*/
/*    -moz-animation: AnimationName 20s ease infinite;*/
/*    animation: AnimationName 20s ease infinite;*/
/*}*/

/*@-webkit-keyframes AnimationName {*/
/*    0%{background-position:50% 0%}*/
/*    50%{background-position:50% 100%}*/
/*    100%{background-position:50% 0%}*/
/*}*/
/*@-moz-keyframes AnimationName {*/
/*    0%{background-position:50% 0%}*/
/*    50%{background-position:50% 100%}*/
/*    100%{background-position:50% 0%}*/
/*}*/
/*@keyframes AnimationName {*/
/*    0%{background-position:50% 0%}*/
/*    50%{background-position:50% 100%}*/
/*    100%{background-position:50% 0%}*/
/*}*/
```
